### ISSUE TITLE
esse projeto está ativo?

### ISSUE THREAD

**Issue by ghost** [AllanSmithll/ProtocolosdeRedes#1]
Olá a todos.

esse projeto está ativo?

*gostaria de contribuir com algumas ideias*

**Comment by AllanSmithll** [comment]
Desculpe por não respondê-lo rapidamente. Estamos de férias hahaha.

Na verdade, é apenas um repositório para pôr as atividades desenvolvidas em sala de aula. Não é bem um "projeto".

**Comment by ghost** [comment]
Oi AllanSmithll.

> Desculpe por não respondê-lo rapidamente. Estamos de férias hahaha.

de boas mano.

> Na verdade, é apenas um repositório para pôr as atividades desenvolvidas em sala de aula. Não é bem um "projeto".

Achei maneiro teu projeto, queria adicionar exemplos de protocolos de rede como ftp, webdav etc.

*O que você pensa ou acha dessa ideia de ter mais exemplos protocolos de rede nesse repositório? a ideia é boa ou ruim?*

**Comment by AllanSmithll** [comment]
É uma ótima ideia sim. Vou te colocar como colaborador, de qualquer forma.

**Comment by ghost** [comment]
Oi AllanSmithll.

> É uma ótima ideia sim. Vou te colocar como colaborador, de qualquer forma.

Muito obrigado pela oportunidade e por aceitar minha ideia.

**Atualização:** Fiz alguns pull-requests e commits, por favor quando tiver tempo avalia essas ideias.

**Comment by AllanSmithll** [comment]
Vi tudo. Está mandando bem! 👌👏

**Comment by ghost** [comment]
Oi AllanSmithll.

> Vi tudo. Está mandando bem! 👌👏

Valeu pela confiança. 

Num futuro próximo, podemos criar um minicurso online sobre Protocolos de Redes. Não sei se já pensou nisso. Minha ideia geral é falar das configurações dos protocolos de redes, casos de uso e outras informações relevantes - e públicas. Dessa forma, pessoas comuns ou programadores podem ter melhor direcionamento na escolha de um ou mais protocolos de rede.

*Inicialmente podemos criar um site no GitHub Pages com docsify*

Um exemplo dessa ideia seria algo como: `allansmithll.github.io/protocolosderedes` ou `protocolosderedes.github.io`

**Comment by AllanSmithll** [comment]
Desculpe, cara. Você está querendo ir longe demais com meu repositório. Melhor fazer essas suas ideias num repositório próprio. São ideias de alto nível, que não estão no meu foco atual. Enfim, se cuida.
